// Generated by CoffeeScript 2.7.0
(function() {
  var i, len, num, nums;

  nums = [10, 20, 30];

  for (i = 0, len = nums.length; i < len; i++) {
    num = nums[i];
    console.log(num);
  }

}).call(this);
